# Generated by Django 6.1 on 2026-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
