# Generated by Django 6.1 on 2026-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_reviewed', 'Application Reviewed'), ('application_accepted', 'Application Accepted'), ('application_rejected', 'Application Rejected'), ('job_posted', 'Job Posted'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('application_shortlisted', 'Application Shortlisted'), ('application_interview', 'Application Interview'), ('application_offer', 'Job Offer'), ('application_hired', 'Application Hired'), ('application_withdrawn', 'Application Withdrawn')], max_length=50),
        ),
    ]
