# Generated by Django 6.1 on 2026-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_reviewed', 'Application Reviewed'), ('application_shortlisted', 'Application Shortlisted'), ('application_interview', 'Application Interview'), ('application_offer', 'Job Offer'), ('application_hired', 'Application Hired'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('application_accepted', 'Application Accepted'), ('job_posted', 'Job Posted'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected')], max_length=50),
        ),
    ]
