# Generated by Django 6.1 on 2026-09-10 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_reviewed', 'Application Reviewed'), ('application_shortlisted', 'Application Shortlisted'), ('application_interview', 'Application Interview'), ('application_offer', 'Job Offer'), ('application_hired', 'Application Hired'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('application_accepted', 'Application Accepted'), ('job_posted', 'Job Posted'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('interview_rescheduled', 'Interview Rescheduled'), ('interview_cancelled', 'Interview Cancelled'), ('interview_completed', 'Interview Completed')], max_length=50),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.application')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
