# Generated by Django 6.1 on 2026-09-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_notification_notification_type_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='attendance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_response_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='reschedule_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('declined', 'Declined')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_reviewed', 'Application Reviewed'), ('application_shortlisted', 'Application Shortlisted'), ('application_interview', 'Application Interview'), ('application_offer', 'Job Offer'), ('application_hired', 'Application Hired'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('application_accepted', 'Application Accepted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_rescheduled', 'Interview Rescheduled'), ('interview_cancelled', 'Interview Cancelled'), ('interview_completed', 'Interview Completed'), ('interview_confirmed', 'Interview Confirmed'), ('interview_reschedule_requested', 'Interview Reschedule Requested'), ('interview_declined', 'Interview Declined'), ('interview_reminder', 'Interview Reminder'), ('job_posted', 'Job Posted'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected')], max_length=50),
        ),
    ]
