# Generated by Django 6.1 on 2026-09-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_reviewed', 'Application Reviewed'), ('application_shortlisted', 'Application Shortlisted'), ('application_interview', 'Application Interview'), ('application_offer', 'Job Offer'), ('application_hired', 'Application Hired'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('application_accepted', 'Application Accepted'), ('job_posted', 'Job Posted'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('interview_rescheduled', 'Interview Rescheduled'), ('interview_cancelled', 'Interview Cancelled'), ('interview_completed', 'Interview Completed'), ('interview_attendance_confirmed', 'Interview Attendance Confirmed'), ('interview_declined', 'Interview Declined'), ('interview_reschedule_requested', 'Interview Reschedule Requested'), ('interview_reschedule_approved', 'Interview Reschedule Approved'), ('interview_reschedule_rejected', 'Interview Reschedule Rejected')], max_length=50),
        ),
    ]
