# Generated by Django 6.1 on 2026-09-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_interview_preferred_date_interview_preferred_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
