# Generated by Django 6.1 on 2026-09-11 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_company_is_suspended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_suspended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_deactivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_reviewed', 'Application Reviewed'), ('application_shortlisted', 'Application Shortlisted'), ('application_interview', 'Application Interview'), ('application_offer', 'Job Offer'), ('application_hired', 'Application Hired'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('application_accepted', 'Application Accepted'), ('job_posted', 'Job Posted'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('interview_rescheduled', 'Interview Rescheduled'), ('interview_cancelled', 'Interview Cancelled'), ('interview_completed', 'Interview Completed'), ('interview_attendance_confirmed', 'Interview Attendance Confirmed'), ('interview_declined', 'Interview Declined'), ('interview_reschedule_requested', 'Interview Reschedule Requested'), ('interview_reschedule_approved', 'Interview Reschedule Approved'), ('interview_reschedule_rejected', 'Interview Reschedule Rejected'), ('employer_suspended', 'Employer Suspended'), ('employer_reactivated', 'Employer Reactivated'), ('company_suspended', 'Company Suspended'), ('company_reactivated', 'Company Reactivated'), ('account_deactivated', 'Account Deactivated'), ('account_reactivated', 'Account Reactivated')], max_length=50),
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_deactivated', 'User Deactivated'), ('user_reactivated', 'User Reactivated'), ('user_deleted', 'User Deleted'), ('employer_suspended', 'Employer Suspended'), ('employer_reactivated', 'Employer Reactivated'), ('company_suspended', 'Company Suspended'), ('company_reactivated', 'Company Reactivated'), ('company_deactivated', 'Company Deactivated'), ('company_reactivated', 'Company Reactivated'), ('company_deleted', 'Company Deleted'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('job_deleted', 'Job Deleted'), ('application_updated', 'Application Updated')], max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('target_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to='jobs.company')),
                ('target_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to='jobs.job')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
