# Generated by Django 6.1 on 2026-09-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_remove_conversation_user_conversation_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer')], default='job_seeker', max_length=20),
        ),
    ]
